##
##    stack-gatekeeper.yml
##
##    Orchestration file
##
##    This is the stack that runs Cassiny.io
##    :copyright: (c) 2017, Cassiny.io OÜ.
##    All rights reserved.
##
################################################

version: "3.4"

services:

########### TRAEFIK ###########
# https://hub.docker.com/r/library/traefik/
  traefik:
    image: traefik:v1.4.5
    networks:
      - cassiny-private
      - cassiny-public
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: cassiny_io_key
        target: /keys/cassiny_io.key
      - source: cassiny_io_cert
        target: /keys/cassiny_io.cert

      - source: cssny_space_key
        target: /keys/cssny_space.key
      - source: cssny_space_cert
        target: /keys/cssny_space.cert

    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
          - node.labels.gpu == false
    configs:
      - source: traefik
        target: /etc/traefik/traefik.toml

configs:
  traefik:
    file: traefik.toml

networks:
    cassiny-private:
      external: True
    cassiny-public:
      external: True

secrets:
  cassiny_io_key:
    file: ./secrets/cassiny.io.key
  cassiny_io_cert:
    file: ./secrets/cassiny.io.cer
  cssny_space_key:
    file: ./secrets/cssny.space.key
  cssny_space_cert:
    file: ./secrets/cssny.space.cer
