################################################################
# Global configuration
################################################################

debug = false
logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]
[entryPoints]
    [entryPoints.http]
    address = ":80"
    compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    compress = true
        [entryPoints.https.tls]

################################################################
# Consul KV configuration backend
################################################################

# Enable Consul KV configuration backend.
[consul]

endpoint = "consul:8500"
watch = true
prefix = "traefik"

################################################################
# To activate web administration
################################################################

[web]

address = ":8080"

################################################################
# Docker configuration backend
################################################################

[docker]

endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
swarmmode = true

################################################################
# Acme configuration backend
################################################################

[acme]

OnHostRule = true

email = "barrachri@gmail.com"
storage = "traefik/acme/account"
entryPoint = "https"
acmeLogging = true

# CA server to use.
# - Uncomment the line to run on the staging let's encrypt server.
# - Leave comment to go to prod.
#
# Optional
#
# caServer = "https://acme-staging.api.letsencrypt.org/directory"

# List of domains and subdomains for SSL certs

[[acme.domains]]
main = "cassiny.io"
sans = ["www.cassiny.io","mcc.cassiny.io","docs.cassiny.io","registry.cassiny.io","webhooks.cassiny.io"]

[[acme.domains]]
main = "getcassiny.com"
sans = ["www.getcassiny.com"]

[[acme.domains]]
main = "cssny.space"
sans = ["www.cssny.space", "generate.cssny.space"]
