################################################################
# Global configuration
################################################################

debug = false
logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]
[entryPoints]
    [entryPoints.http]
    address = ":80"
    compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
    compress = true
        [entryPoints.https.tls]
            [[entryPoints.https.tls.certificates]]
            # mcc.cassiny.io, registry.cassiny.io, webhooks.cassiny.io
            CertFile = "/keys/cassiny_io.cert"
            KeyFile = "/keys/cassiny_io.key"

            [[entryPoints.https.tls.certificates]]
            # cssny.space, www.cssny.space
            CertFile = "/keys/cssny_space.cert"
            KeyFile = "/keys/cssny_space.key"


################################################################
# To activate web administration
################################################################

[web]

address = ":8080"

################################################################
# Docker configuration backend
################################################################

[docker]

endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
swarmmode = true
