################################################################
# Global configuration
################################################################

debug = true
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]
[entryPoints]
    [entryPoints.http]
    address = ":80"
    compress = true
    [entryPoints.https]
    address = ":443"
    compress = true

################################################################
# Consul KV configuration backend
################################################################

# Enable Consul KV configuration backend.
[consul]

endpoint = "consul:8500"
watch = true
prefix = "traefik"

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]
address = ":8080"
readOnly = true

################################################################
# Docker configuration backend
################################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
swarmmode = true
