##
##    stack-frontenders.yml
##
##    Orchestration file
##
##    This is the stack that runs Cassiny.io
##    :copyright: (c) 2017, Cassiny.io OÜ.
##    All rights reserved.
##
################################################

version: "3.4"

services:

########### mcc.cassiny.io ###########
# https://hub.docker.com/r/cassinyio/mcc-cassiny-io/
  mcc-cassiny-io:
    image: cassinyio/mcc-cassiny-io:latest
    networks:
      - cassiny-private
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.labels.gpu == false
      labels:
        traefik.port: "8043"
        traefik.enable: "true"
        traefik.frontend.rule: "Host:mcc.cassiny.io"

networks:
    cassiny-private:
      external: True
