################################################
##
##    stack-services.yml
##
##    Orchestration file
##
##    :copyright: (c) 2017, Cassiny.io OÜ.
##    All rights reserved.
##
################################################

version: "3.4"

services:

########### cassiny-auth ###########
# https://hub.docker.com/r/cassinyio/cassiny-auth/
  cassiny-auth:
    image: cassinyio/cassiny-auth:fae5010
    networks:
      - cassiny-private
      - cassiny-public
    env_file:
     - ../environment/.env
    secrets:
      - source: private_key
        target: /src/keys/private.key
      - source: public_key
        target: /src/keys/public.key
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.gpu == false
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "8080"
        traefik.enable: "true"
        traefik.frontend.rule: "Host:mcc.cassiny.io;PathPrefix: /api/auth"
        traefik.docker.network: "cassiny-private"


########### cassiny-spawner ###########
# https://hub.docker.com/r/cassinyio/cassiny-spawner/
  cassiny-spawner:
    image: cassinyio/cassiny-spawner:24fafe5
    networks:
      - cassiny-private
    env_file:
      - ../environment/.env
    secrets:
      - source: public_key
        target: /src/keys/public.key
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.gpu == false
          - node.role == manager
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "8080"
        traefik.enable: "true"
        traefik.frontend.rule: "Host:mcc.cassiny.io;PathPrefix: /api/spawner"
        traefik.docker.network: "cassiny-private"

########### cassiny-infrastructure ###########
# https://hub.docker.com/r/cassinyio/cassiny-infrastructure/
  cassiny-infrastructure:
    image: cassinyio/cassiny-infrastructure:0e155224
    networks:
      - cassiny-private
    env_file:
      - ../environment/.env
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.gpu == false
          - node.role == manager
      mode: replicated
      replicas: 1

########### cassiny-watcher ###########
# https://hub.docker.com/r/cassinyio/cassiny-watcher/
  cassiny-auth:
    image: cassinyio/cassiny-watcher:204dee2
    networks:
      - cassiny-private
    env_file:
     - ../environment/.env
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.gpu == false
      mode: global

########### cassiny-webhooks ###########
# https://hub.docker.com/r/cassinyio/cassiny-webhooks/
  cassiny-webhooks:
    image: cassinyio/cassiny-webhooks:cb73a7e
    networks:
      - cassiny-private
    env_file:
      - ../environment/.env
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
          - node.labels.gpu == false
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "8080"
        traefik.enable: "true"
        traefik.frontend.rule: "Host:webhooks.cassiny.io"
        traefik.docker.network: "cassiny-private"

networks:
    cassiny-private:
      external: True
    cassiny-public:
      external: True

secrets:
  public_key:
    file: ./secrets/public.key
  private_key:
    file: ./secrets/private.key
